### PR TITLE
Refactor promises

### LINKED ISSUE #10: Promise usage
Hi, thanks for the nice library! 

In the code you create a `resolvable()`  only to resolve it with an already existing promise which [is not something you typically have to do](https://stackoverflow.com/questions/23803743/what-is-the-explicit-promise-construction-antipattern-and-how-do-i-avoid-it?noredirect=1#comment78892479_23803743). 

You can use `fetch` as `this.response`, the `setTimeout` also isn't necessary as promises take care of reacting on the next tick anyway.

I'll write a PR to illustrate what I mean

### PR DESCRIPTION
**Pull request by benjamingr**
Refactor promise usage in the code - removing the `resolvable()` function and `return`ing from `fetch` which already returns a promise.

I wonder if this helps with the file size :)

Fixes #10

### CODE REVIEW

**Comment by mikeal** [comment]
Travis is broken right now cause of a config issue I can't resolve until I get the npm name, are all the tests passing?

**Comment by benjamingr** [comment]
Yes, at least on my machine. I wouldn't submit a PR otherwise without saying so.

This is not urgent - it's a code style fix so there is no rush about it.

Let me know if there is any help I can offer with the CI - I'm generally bad with CIs so I try to pick up opportunities to learn.

**Comment by benjamingr** [comment]
Hey @mikeal are you still looking into integrating this? Let me know if I should resolve the conflicts and continue work. Again - only if this works out for you and feel free to say you don't have time/motivation to work on this and I'll drop it with no hard feelings <3

**Comment by mikeal** [comment]
yes, i would love to merge this :)

**Comment by ewolfe** [comment]
@benjamingr thanks for working on this, would you mind fixing the conflicting files?

**Comment by benjamingr** [comment]
Sorry, forgot about this - just did the change again and force pushed.

**Comment by ewolfe** [comment]
Looks like this is good to go @mikeal

**Pull request merged**
